# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificate', '0002_auto_20161222_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='path',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='module',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=255, verbose_name='Модуль модели'),
            preserve_default=False,
        ),
    ]
