# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Имя')),
                ('date_joined', models.DateField(verbose_name='Дата регистрации')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('status', models.CharField(max_length=160, verbose_name='Статус')),
                ('about', models.TextField(max_length=160, verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UsersBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('fav', models.BooleanField(default=False, verbose_name='Любимая')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитана')),
                ('wish', models.BooleanField(default=False, verbose_name='Хочу прочитаь')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
