# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['created'], 'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
    ]
