# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('cover', models.ImageField(blank=True, upload_to='', verbose_name='Обложка')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('data_creation', models.DateField(blank=True, verbose_name='Дата создания')),
                ('editor', models.CharField(blank=True, max_length=255, verbose_name='Редактор')),
                ('publish', models.CharField(blank=True, max_length=100, verbose_name='Издательство')),
                ('description', models.TextField(verbose_name='Описание')),
                ('where_buy', models.CharField(blank=True, max_length=255, verbose_name='Где купить')),
                ('film', models.CharField(blank=True, max_length=100, verbose_name='По ней снят фильм')),
            ],
        ),
    ]
