# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateField(verbose_name='Название жанра')),
            ],
            options={
                'verbose_name_plural': 'Жанры',
                'ordering': ['title'],
                'verbose_name': 'Жанр',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='books.Genre', verbose_name='Жанр(ы)'),
        ),
    ]
