# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161210_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название жанра'),
        ),
    ]
