# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 12:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_auto_20161210_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'ordering': ['name'],
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название подборки')),
            ],
            options={
                'verbose_name': 'Подборка',
                'ordering': ['name'],
                'verbose_name_plural': 'Подборки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание рецензии')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'ordering': ['date_created'],
                'verbose_name_plural': 'Рецензии',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='data_creation',
        ),
        migrations.AddField(
            model_name='book',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 17, 12, 15, 45, 369587, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='К какой книге рецензия'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='collection',
            name='books',
            field=models.ManyToManyField(to='books.Book', verbose_name='Книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='books.Author', verbose_name='Автор(ы)'),
        ),
    ]
