# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20161220_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Доступна на сайте'),
        ),
    ]
